language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: tictactoe-gryffindor
  api_key:
    secure: PHe96ue2TaZI1Dw1gNmOD6F/EdpjMemn+qt5bfyg4oq+KsPqj9Xac1kPR3RNN6bWPvgs5ZAmBMDvvqMoNxQ8WwRWofnExSuLvey1AcKo9OGjouMEM9wX4gyu7d3D++XQaunsFcOYF3dhDz4/r4HT4PBpWpJ89FQvj6OUnE/f2xeUdyN+y224t9mCGjZWlCi7mgPTvW5Fk0I6DMggQpP7guMT2LEybUVEiAyYdy6ji596bidQ4BsgbQwzJ8bDLYPURaRRBG6wqKBo9rVE5Sv82z5CF6wtwOyUnkMALqPl72+qjvtitSA0ufRvnoA96aavTmmLM7VBX5E8tA0BqffxWRFYDMBa8AauOvRdKQijbIELxylK2aML82mYNyvihOdAHbwFMi4yMvvPn2pJ2xG3gd5kzH/BHFR8jrXsN9maAWeqDKsusiKqTgGWg+tZAsk0kJaRBjt7Bvp7mnyyIFrbvnWaM9WVlXz4wsnFKBr2Zf3cXLwOYJxdPo5gyrJWnP93TluFOwcoAX4Cs0Ybi6zZ7fp/dEOlmHZvDZMa4BFNaDSLwR9gx5Fchj9JwqaXbaRa3HQaw161AwNLf1ZcCkBy/aa1F82yxgq7Auad5S+tt6J7wWOi/7d5UFA60/NM0hglcjCjRUldt7vTo517rnaeTfu/UtvdHo45q48QGDiu7PQ=
